imports = ["services/postgres"]

[devshell]
packages = [
  "erlang",
  "libnotify",
  "inotify-tools",
  "nodejs",
  "elixir_ls",
  "nodePackages.pnpm",
  "gnumake",
  "gcc"
]
[services.postgres]
initdbArgs = ["--no-locale", "--encoding=UTF-8"]

[[env]]
name = "HEX_HOME"
eval = "${PWD}/.nix/hex"

[[env]]
name = "MIX_HOME"
eval = "${PWD}/.nix/mix"

[[env]]
name = "PATH"
prefix = "${MIX_HOME}/escripts"

[[env]]
name = "ERL_AFLAGS"
value = "-kernel shell_history enabled"

[[commands]]
name = "mix"
package = "elixir"
help = "mix"

[[commands]]
name = "startdb"
category = "db"
command = "pg_ctl start"
help = "Start postgres"

[[commands]]
name = "stopdb"
category = "db"
command = "pg_ctl stop"
help = "Stop postgres"
