[devshell]
packages = [
  "erlang",
  "libnotify",
  "inotify-tools",
  "elixir_ls",
]

[[env]]
name = "HEX_HOME"
eval = "${PWD}/.nix/hex"

[[env]]
name = "MIX_HOME"
eval = "${PWD}/.nix/mix"

[[env]]
name = "PATH"
prefix = "${MIX_HOME}/escripts"

[[env]]
name = "ERL_AFLAGS"
value = "-kernel shell_history enabled"

[[commands]]
name = "mix"
package = "elixir"
help = "mix"
